version: '3'

services:
  web:
    build:
      context: .
      dockerfile: packaging/docker/Dockerfile
    environment:
      ENVIRONMENT: dev
    env_file:
      - .env
    volumes:
      - ./src/hausmans:/app
    ports:
      - "8000:8000"
