version: '3'

services:
  web:
    build:
      context: .
      dockerfile: packaging/docker/Dockerfile
    environment:
      ENVIRONMENT: prod
    env_file:
      - .env
    volumes:
      - ./src/hausmans:/app
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./packaging/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./packaging/conf/nginx/self-signed.conf:/etc/nginx/snippets/self-signed.conf
      - ./packaging/conf/nginx/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
      - ./packaging/data/certbot/conf:/etc/letsencrypt
      - ./packaging/data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./packaging/data/certbot/conf:/etc/letsencrypt
      - ./packaging/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
