# Generated by Django 3.1 on 2020-12-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0004_portfolioproject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='project_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='thumbnail_image',
            field=models.ImageField(upload_to='portfolio_images', verbose_name='Main Image'),
        ),
    ]
